# Generated by Django 5.0.7 on 2026-08-16 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCareLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('VENDING_MACHINE', 'Pad Vending Machine'), ('MEDICAL_STORE', 'Medical Store'), ('PHARMACY', 'Pharmacy'), ('WOMEN_CARE_CENTER', 'Women Care Center')], db_index=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='women_safet_categor_f3a985_idx'), models.Index(fields=['latitude', 'longitude'], name='women_safet_latitud_f3a6bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PinkHelpPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_staffed_24x7', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='women_safet_latitud_836c63_idx')],
            },
        ),
    ]
