# Generated by Django 5.0.7 on 2026-08-16 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('restroom_type', models.CharField(choices=[('RAILWAY', 'Railway Station'), ('HIGHWAY', 'Highway')], db_index=True, max_length=10)),
                ('station_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('station_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('platform_number', models.CharField(blank=True, max_length=10)),
                ('highway_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_women_only', models.BooleanField(default=False)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('has_baby_care', models.BooleanField(default=False)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_fuel_station', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cleanliness_rating', models.DecimalField(decimal_places=2, default=0, help_text='Denormalized average of RestroomRating.cleanliness_score for fast list/filter queries.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cleanliness_rating', 'name'],
                'indexes': [models.Index(fields=['restroom_type', 'is_active'], name='restrooms_r_restroo_282271_idx'), models.Index(fields=['latitude', 'longitude'], name='restrooms_r_latitud_5315b7_idx'), models.Index(fields=['cleanliness_rating'], name='restrooms_r_cleanli_5e7929_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestroomRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleanliness_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('safety_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restrooms.restroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restroom_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='restroomrating',
            constraint=models.UniqueConstraint(fields=('restroom', 'user'), name='one_rating_per_user_per_restroom'),
        ),
    ]
